#include "stdafx.h"
#include "IOList_shortcuts_auto_created.h"
#include "IORegister.h"
#include "IOList.h"

//The following code is automatically created and provides you quick and easy access to all outputs defined in ControlUserIOConfig.json.
//These shortcuts are only useful if you use the .exe version of control,
//they are not necessary when using the .dll version.

//The reason to use these shortcuts is that they provide a 2...3x faster access to the output channels defined in UserIOConfig.json.
//Alternatively, you could access these channels somewhat slowly using: 
//  AnalogOut("SetNAME_OF_OUTPUT", Voltage);
//  DigitalOut("SetNAME_OF_OUTPUT", OnOff);
//Duration in Debug mode:   800ns for direct access, 2800ns when using Analog/DigitalOut().
//Duration in Release mode: 160ns for direct access,  360ns when using Analog/DigitalOut().

// The shortcut code is created on program start and stored in [DebugFolder]\IOList_shortcuts_auto_create.h and .cpp,
// if the option to create these files is enabled in the configuration file
// ControlParam_SystemParamList.txt, i.e. if in that file we have the line
// DoCreateIOListShortcuts = TRUE
// You can also define the [DebugFolder] there, by modifying the line
// DebugFilePath=D:\DebugFiles\

//To use the shortcuts, copy the files IOList_shortcuts_auto_create.h and .cpp into the source folder of Control.

AnalogOutFuncShortcut SetMOTCoilCurrent;
AnalogOutFuncShortcut SetChillerSetpoint;
AnalogOutFuncShortcut SetLatticePowerSetpoint;
AnalogOutFuncShortcut SetPMTGain;
AnalogOutFuncShortcut SetElectrodeAVoltage;
AnalogOutFuncShortcut SetElectrodeBVoltage;
AnalogOutFuncShortcut SetElectrodeCVoltage;
AnalogOutFuncShortcut SetTestAnalogOut;
DigitalOutFuncShortcut SwitchOscilloscopeTrigger;
DigitalOutFuncShortcut SwitchCameraTrigger0;
DigitalOutFuncShortcut SwitchCameraTrigger1;
DigitalOutFuncShortcut SwitchPMTTrigger;
DigitalOutFuncShortcut SwitchMOTCoilsToHelmholtz;
DigitalOutFuncShortcut SwitchElectrodeA;
DigitalOutFuncShortcut SwitchElectrodeB;
DigitalOutFuncShortcut SwitchElectrodeC;
DigitalOutFuncShortcut SwitchBiasX;
DigitalOutFuncShortcut SwitchBiasY;
DigitalOutFuncShortcut SwitchBiasZ;
DigitalOutFuncShortcut SwitchTorunCoilDriverD0;
DigitalOutFuncShortcut SwitchTorunCoilDriverD1;
DigitalOutFuncShortcut SwitchTorunCoilDriverD2;
DigitalOutFuncShortcut SwitchTorunCoilDriverTrigger;
DigitalOutFuncShortcut Switch10MHzRfSourceSelection;
DigitalOutFuncShortcut SwitchBlueDetectionShutter;
DigitalOutFuncShortcut SwitchBlueMOTShutter;
DigitalOutFuncShortcut SwitchZSShutter;
DigitalOutFuncShortcut SwitchRedMOTShutter;
DigitalOutFuncShortcut SwitchRedPumpShutter;
DigitalOutFuncShortcut SwitchPumpPolarization1Shutter;
DigitalOutFuncShortcut SwitchPumpPolarization2Shutter;
DigitalOutFuncShortcut SwitchCoarseSpectroscopyShutter;
AnalogOutFuncShortcut SetIntensityCoarseSpectroscopyAOM;
AnalogOutFuncShortcut SetStartFrequencyCoarseSpectroscopyAOM;
AnalogOutFuncShortcut SetStopFrequencyCoarseSpectroscopyAOM;
AnalogOutFuncShortcut SetModulationFrequencyCoarseSpectroscopyAOM;
AnalogOutFuncShortcut SetFSKModeCoarseSpectroscopyAOM;
AnalogOutFuncShortcut SetRampRateClockCoarseSpectroscopyAOM;
DigitalOutFuncShortcut SetClearACC1CoarseSpectroscopyAOM;
DigitalOutFuncShortcut SetTriangleBitCoarseSpectroscopyAOM;
DigitalOutFuncShortcut SetFSKBitCoarseSpectroscopyAOM;
AnalogOutFuncShortcut SetIntensityClockSteeringAOM;
AnalogOutFuncShortcut SetStartFrequencyClockSteeringAOM;
AnalogOutFuncShortcut SetStopFrequencyClockSteeringAOM;
AnalogOutFuncShortcut SetModulationFrequencyClockSteeringAOM;
AnalogOutFuncShortcut SetFSKModeClockSteeringAOM;
AnalogOutFuncShortcut SetRampRateClockClockSteeringAOM;
DigitalOutFuncShortcut SetClearACC1ClockSteeringAOM;
DigitalOutFuncShortcut SetTriangleBitClockSteeringAOM;
DigitalOutFuncShortcut SetFSKBitClockSteeringAOM;
AnalogOutFuncShortcut SetIntensityClockSpectroscopyDDS;
AnalogOutFuncShortcut SetStartFrequencyClockSpectroscopyDDS;
AnalogOutFuncShortcut SetStopFrequencyClockSpectroscopyDDS;
AnalogOutFuncShortcut SetModulationFrequencyClockSpectroscopyDDS;
AnalogOutFuncShortcut SetFSKModeClockSpectroscopyDDS;
AnalogOutFuncShortcut SetRampRateClockClockSpectroscopyDDS;
DigitalOutFuncShortcut SetClearACC1ClockSpectroscopyDDS;
DigitalOutFuncShortcut SetTriangleBitClockSpectroscopyDDS;
DigitalOutFuncShortcut SetFSKBitClockSpectroscopyDDS;
AnalogOutFuncShortcut SetIntensityClockSpectroscopyDDSfixed40MHz;
AnalogOutFuncShortcut SetStartFrequencyClockSpectroscopyDDSfixed40MHz;
AnalogOutFuncShortcut SetStopFrequencyClockSpectroscopyDDSfixed40MHz;
AnalogOutFuncShortcut SetModulationFrequencyClockSpectroscopyDDSfixed40MHz;
AnalogOutFuncShortcut SetFSKModeClockSpectroscopyDDSfixed40MHz;
AnalogOutFuncShortcut SetRampRateClockClockSpectroscopyDDSfixed40MHz;
DigitalOutFuncShortcut SetClearACC1ClockSpectroscopyDDSfixed40MHz;
DigitalOutFuncShortcut SetTriangleBitClockSpectroscopyDDSfixed40MHz;
DigitalOutFuncShortcut SetFSKBitClockSpectroscopyDDSfixed40MHz;
AnalogOutFuncShortcut SetIntensityRedMOTAOM;
AnalogOutFuncShortcut SetStartFrequencyRedMOTAOM;
AnalogOutFuncShortcut SetStopFrequencyRedMOTAOM;
AnalogOutFuncShortcut SetModulationFrequencyRedMOTAOM;
AnalogOutFuncShortcut SetFSKModeRedMOTAOM;
AnalogOutFuncShortcut SetRampRateClockRedMOTAOM;
DigitalOutFuncShortcut SetClearACC1RedMOTAOM;
DigitalOutFuncShortcut SetTriangleBitRedMOTAOM;
DigitalOutFuncShortcut SetFSKBitRedMOTAOM;
AnalogOutFuncShortcut SetIntensityRedPumpAOM;
AnalogOutFuncShortcut SetStartFrequencyRedPumpAOM;
AnalogOutFuncShortcut SetStopFrequencyRedPumpAOM;
AnalogOutFuncShortcut SetModulationFrequencyRedPumpAOM;
AnalogOutFuncShortcut SetFSKModeRedPumpAOM;
AnalogOutFuncShortcut SetRampRateClockRedPumpAOM;
DigitalOutFuncShortcut SetClearACC1RedPumpAOM;
DigitalOutFuncShortcut SetTriangleBitRedPumpAOM;
DigitalOutFuncShortcut SetFSKBitRedPumpAOM;
AnalogOutFuncShortcut SetIntensityPumpDPAOM;
AnalogOutFuncShortcut SetStartFrequencyPumpDPAOM;
AnalogOutFuncShortcut SetStopFrequencyPumpDPAOM;
AnalogOutFuncShortcut SetModulationFrequencyPumpDPAOM;
AnalogOutFuncShortcut SetFSKModePumpDPAOM;
AnalogOutFuncShortcut SetRampRateClockPumpDPAOM;
DigitalOutFuncShortcut SetClearACC1PumpDPAOM;
DigitalOutFuncShortcut SetTriangleBitPumpDPAOM;
DigitalOutFuncShortcut SetFSKBitPumpDPAOM;
AnalogOutFuncShortcut SetFrequencyBlueMOTDPAOM;
AnalogOutFuncShortcut SetIntensityBlueMOTDPAOM;
AnalogOutFuncShortcut SetFrequencyBlueDetectionDPAOM;
AnalogOutFuncShortcut SetIntensityBlueDetectionDPAOM;
AnalogOutFuncShortcut SetFrequencyLatticeAOM;
AnalogOutFuncShortcut SetIntensityLatticeAOM;
AnalogOutFuncShortcut SetFrequencyLatticeEOM;
AnalogOutFuncShortcut SetIntensityLatticeEOM;
AnalogOutFuncShortcut SetFrequencyCh0ClockPDHDDS;
AnalogOutFuncShortcut SetIntensityCh0ClockPDHDDS;
AnalogOutFuncShortcut SetFrequencyCh1ClockPDHDDS;
AnalogOutFuncShortcut SetIntensityCh1ClockPDHDDS;
AnalogOutFuncShortcut SetPhaseCh1ClockPDHDDS;
AnalogOutFuncShortcut SetIntensityUserIOTestDDSAD9854_0;
AnalogOutFuncShortcut SetStartFrequencyTuningWordUserIOTestDDSAD9854_0;
AnalogOutFuncShortcut SetStopFrequencyTuningWordUserIOTestDDSAD9854_0;
AnalogOutFuncShortcut SetModulationFrequencyUserIOTestDDSAD9854_0;
AnalogOutFuncShortcut SetFSKModeUserIOTestDDSAD9854_0;
AnalogOutFuncShortcut SetRampRateClockUserIOTestDDSAD9854_0;
DigitalOutFuncShortcut SetClearACC1UserIOTestDDSAD9854_0;
DigitalOutFuncShortcut SetTriangleBitUserIOTestDDSAD9854_0;
DigitalOutFuncShortcut SetFSKBitUserIOTestDDSAD9854_0;
AnalogOutFuncShortcut SetFrequencyUserIOTestDDSAD9858_0;
AnalogOutFuncShortcut SetAttenuationUserIOTestDDSAD9858_0;
AnalogOutFuncShortcut SetFrequencyCh0UserIOTestDDSAD9958_0;
AnalogOutFuncShortcut SetIntensityCh0UserIOTestDDSAD9958_0;
AnalogOutFuncShortcut SetFrequencyCh1UserIOTestDDSAD9958_0;
AnalogOutFuncShortcut SetIntensityCh1UserIOTestDDSAD9958_0;
AnalogOutFuncShortcut SetPhaseCh1UserIOTestDDSAD9958_0;
AnalogOutFuncShortcut SetSpareAnalogOut0;
AnalogOutFuncShortcut SetSpareAnalogOut1;
AnalogOutFuncShortcut SetSpareAnalogOut2;
AnalogOutFuncShortcut SetSpareAnalogOut3;
AnalogOutFuncShortcut SetSpareAnalogOut4;
AnalogOutFuncShortcut SetSpareAnalogOut5;
AnalogOutFuncShortcut SetSpareAnalogOut6;
AnalogOutFuncShortcut SetSpareAnalogOut7;
DigitalOutFuncShortcut SwitchSpareDigitalOut0;
DigitalOutFuncShortcut SwitchSpareDigitalOut1;
DigitalOutFuncShortcut SwitchSpareDigitalOut2;
DigitalOutFuncShortcut SwitchSpareDigitalOut3;
DigitalOutFuncShortcut SwitchSpareDigitalOut4;
DigitalOutFuncShortcut SwitchSpareDigitalOut5;
DigitalOutFuncShortcut SwitchSpareDigitalOut6;
DigitalOutFuncShortcut SwitchSpareDigitalOut7;
DigitalOutFuncShortcut SwitchSpareDigitalOut8;
DigitalOutFuncShortcut SwitchSpareDigitalOut9;
DigitalOutFuncShortcut SwitchSpareDigitalOut10;
DigitalOutFuncShortcut SwitchSpareDigitalOut11;
DigitalOutFuncShortcut SwitchSpareDigitalOut12;
DigitalOutFuncShortcut SwitchSpareDigitalOut13;
DigitalOutFuncShortcut SwitchSpareDigitalOut14;
DigitalOutFuncShortcut SwitchSpareDigitalOut15;
DigitalOutFuncShortcut SwitchExtraClockShutter0;
DigitalOutFuncShortcut SwitchExtraClockShutter1;
DigitalOutFuncShortcut SwitchExtraClockShutter2;
DigitalOutFuncShortcut SwitchExtraClockShutter3;
DigitalOutFuncShortcut SwitchExtraClockShutter4;
DigitalOutFuncShortcut SwitchAdditionalShutter0;
DigitalOutFuncShortcut SwitchAdditionalShutter1;
DigitalOutFuncShortcut SwitchAdditionalShutter2;
DigitalOutFuncShortcut SwitchAdditionalShutter3;
DigitalOutFuncShortcut SwitchAdditionalShutter4;
DigitalOutFuncShortcut SwitchAdditionalShutter5;
DigitalOutFuncShortcut SwitchAdditionalShutter6;
DigitalOutFuncShortcut SwitchAdditionalShutter7;

void CIORegister::CreateShortcutsToUserIO() {
	SetMOTCoilCurrent = GetAnalogOutput("SetMOTCoilCurrent");
	SetChillerSetpoint = GetAnalogOutput("SetChillerSetpoint");
	SetLatticePowerSetpoint = GetAnalogOutput("SetLatticePowerSetpoint");
	SetPMTGain = GetAnalogOutput("SetPMTGain");
	SetElectrodeAVoltage = GetAnalogOutput("SetElectrodeAVoltage");
	SetElectrodeBVoltage = GetAnalogOutput("SetElectrodeBVoltage");
	SetElectrodeCVoltage = GetAnalogOutput("SetElectrodeCVoltage");
	SetTestAnalogOut = GetAnalogOutput("SetTestAnalogOut");
	SwitchOscilloscopeTrigger = GetDigitalOutput("SwitchOscilloscopeTrigger");
	SwitchCameraTrigger0 = GetDigitalOutput("SwitchCameraTrigger0");
	SwitchCameraTrigger1 = GetDigitalOutput("SwitchCameraTrigger1");
	SwitchPMTTrigger = GetDigitalOutput("SwitchPMTTrigger");
	SwitchMOTCoilsToHelmholtz = GetDigitalOutput("SwitchMOTCoilsToHelmholtz");
	SwitchElectrodeA = GetDigitalOutput("SwitchElectrodeA");
	SwitchElectrodeB = GetDigitalOutput("SwitchElectrodeB");
	SwitchElectrodeC = GetDigitalOutput("SwitchElectrodeC");
	SwitchBiasX = GetDigitalOutput("SwitchBiasX");
	SwitchBiasY = GetDigitalOutput("SwitchBiasY");
	SwitchBiasZ = GetDigitalOutput("SwitchBiasZ");
	SwitchTorunCoilDriverD0 = GetDigitalOutput("SwitchTorunCoilDriverD0");
	SwitchTorunCoilDriverD1 = GetDigitalOutput("SwitchTorunCoilDriverD1");
	SwitchTorunCoilDriverD2 = GetDigitalOutput("SwitchTorunCoilDriverD2");
	SwitchTorunCoilDriverTrigger = GetDigitalOutput("SwitchTorunCoilDriverTrigger");
	Switch10MHzRfSourceSelection = GetDigitalOutput("Switch10MHzRfSourceSelection");
	SwitchBlueDetectionShutter = GetDigitalOutput("SwitchBlueDetectionShutter");
	SwitchBlueMOTShutter = GetDigitalOutput("SwitchBlueMOTShutter");
	SwitchZSShutter = GetDigitalOutput("SwitchZSShutter");
	SwitchRedMOTShutter = GetDigitalOutput("SwitchRedMOTShutter");
	SwitchRedPumpShutter = GetDigitalOutput("SwitchRedPumpShutter");
	SwitchPumpPolarization1Shutter = GetDigitalOutput("SwitchPumpPolarization1Shutter");
	SwitchPumpPolarization2Shutter = GetDigitalOutput("SwitchPumpPolarization2Shutter");
	SwitchCoarseSpectroscopyShutter = GetDigitalOutput("SwitchCoarseSpectroscopyShutter");
	SetIntensityCoarseSpectroscopyAOM = GetAnalogOutput("SetIntensityCoarseSpectroscopyAOM");
	SetStartFrequencyCoarseSpectroscopyAOM = GetAnalogOutput("SetStartFrequencyCoarseSpectroscopyAOM");
	SetStopFrequencyCoarseSpectroscopyAOM = GetAnalogOutput("SetStopFrequencyCoarseSpectroscopyAOM");
	SetModulationFrequencyCoarseSpectroscopyAOM = GetAnalogOutput("SetModulationFrequencyCoarseSpectroscopyAOM");
	SetFSKModeCoarseSpectroscopyAOM = GetAnalogOutput("SetFSKModeCoarseSpectroscopyAOM");
	SetRampRateClockCoarseSpectroscopyAOM = GetAnalogOutput("SetRampRateClockCoarseSpectroscopyAOM");
	SetClearACC1CoarseSpectroscopyAOM = GetDigitalOutput("SetClearACC1CoarseSpectroscopyAOM");
	SetTriangleBitCoarseSpectroscopyAOM = GetDigitalOutput("SetTriangleBitCoarseSpectroscopyAOM");
	SetFSKBitCoarseSpectroscopyAOM = GetDigitalOutput("SetFSKBitCoarseSpectroscopyAOM");
	SetIntensityClockSteeringAOM = GetAnalogOutput("SetIntensityClockSteeringAOM");
	SetStartFrequencyClockSteeringAOM = GetAnalogOutput("SetStartFrequencyClockSteeringAOM");
	SetStopFrequencyClockSteeringAOM = GetAnalogOutput("SetStopFrequencyClockSteeringAOM");
	SetModulationFrequencyClockSteeringAOM = GetAnalogOutput("SetModulationFrequencyClockSteeringAOM");
	SetFSKModeClockSteeringAOM = GetAnalogOutput("SetFSKModeClockSteeringAOM");
	SetRampRateClockClockSteeringAOM = GetAnalogOutput("SetRampRateClockClockSteeringAOM");
	SetClearACC1ClockSteeringAOM = GetDigitalOutput("SetClearACC1ClockSteeringAOM");
	SetTriangleBitClockSteeringAOM = GetDigitalOutput("SetTriangleBitClockSteeringAOM");
	SetFSKBitClockSteeringAOM = GetDigitalOutput("SetFSKBitClockSteeringAOM");
	SetIntensityClockSpectroscopyDDS = GetAnalogOutput("SetIntensityClockSpectroscopyDDS");
	SetStartFrequencyClockSpectroscopyDDS = GetAnalogOutput("SetStartFrequencyClockSpectroscopyDDS");
	SetStopFrequencyClockSpectroscopyDDS = GetAnalogOutput("SetStopFrequencyClockSpectroscopyDDS");
	SetModulationFrequencyClockSpectroscopyDDS = GetAnalogOutput("SetModulationFrequencyClockSpectroscopyDDS");
	SetFSKModeClockSpectroscopyDDS = GetAnalogOutput("SetFSKModeClockSpectroscopyDDS");
	SetRampRateClockClockSpectroscopyDDS = GetAnalogOutput("SetRampRateClockClockSpectroscopyDDS");
	SetClearACC1ClockSpectroscopyDDS = GetDigitalOutput("SetClearACC1ClockSpectroscopyDDS");
	SetTriangleBitClockSpectroscopyDDS = GetDigitalOutput("SetTriangleBitClockSpectroscopyDDS");
	SetFSKBitClockSpectroscopyDDS = GetDigitalOutput("SetFSKBitClockSpectroscopyDDS");
	SetIntensityClockSpectroscopyDDSfixed40MHz = GetAnalogOutput("SetIntensityClockSpectroscopyDDSfixed40MHz");
	SetStartFrequencyClockSpectroscopyDDSfixed40MHz = GetAnalogOutput("SetStartFrequencyClockSpectroscopyDDSfixed40MHz");
	SetStopFrequencyClockSpectroscopyDDSfixed40MHz = GetAnalogOutput("SetStopFrequencyClockSpectroscopyDDSfixed40MHz");
	SetModulationFrequencyClockSpectroscopyDDSfixed40MHz = GetAnalogOutput("SetModulationFrequencyClockSpectroscopyDDSfixed40MHz");
	SetFSKModeClockSpectroscopyDDSfixed40MHz = GetAnalogOutput("SetFSKModeClockSpectroscopyDDSfixed40MHz");
	SetRampRateClockClockSpectroscopyDDSfixed40MHz = GetAnalogOutput("SetRampRateClockClockSpectroscopyDDSfixed40MHz");
	SetClearACC1ClockSpectroscopyDDSfixed40MHz = GetDigitalOutput("SetClearACC1ClockSpectroscopyDDSfixed40MHz");
	SetTriangleBitClockSpectroscopyDDSfixed40MHz = GetDigitalOutput("SetTriangleBitClockSpectroscopyDDSfixed40MHz");
	SetFSKBitClockSpectroscopyDDSfixed40MHz = GetDigitalOutput("SetFSKBitClockSpectroscopyDDSfixed40MHz");
	SetIntensityRedMOTAOM = GetAnalogOutput("SetIntensityRedMOTAOM");
	SetStartFrequencyRedMOTAOM = GetAnalogOutput("SetStartFrequencyRedMOTAOM");
	SetStopFrequencyRedMOTAOM = GetAnalogOutput("SetStopFrequencyRedMOTAOM");
	SetModulationFrequencyRedMOTAOM = GetAnalogOutput("SetModulationFrequencyRedMOTAOM");
	SetFSKModeRedMOTAOM = GetAnalogOutput("SetFSKModeRedMOTAOM");
	SetRampRateClockRedMOTAOM = GetAnalogOutput("SetRampRateClockRedMOTAOM");
	SetClearACC1RedMOTAOM = GetDigitalOutput("SetClearACC1RedMOTAOM");
	SetTriangleBitRedMOTAOM = GetDigitalOutput("SetTriangleBitRedMOTAOM");
	SetFSKBitRedMOTAOM = GetDigitalOutput("SetFSKBitRedMOTAOM");
	SetIntensityRedPumpAOM = GetAnalogOutput("SetIntensityRedPumpAOM");
	SetStartFrequencyRedPumpAOM = GetAnalogOutput("SetStartFrequencyRedPumpAOM");
	SetStopFrequencyRedPumpAOM = GetAnalogOutput("SetStopFrequencyRedPumpAOM");
	SetModulationFrequencyRedPumpAOM = GetAnalogOutput("SetModulationFrequencyRedPumpAOM");
	SetFSKModeRedPumpAOM = GetAnalogOutput("SetFSKModeRedPumpAOM");
	SetRampRateClockRedPumpAOM = GetAnalogOutput("SetRampRateClockRedPumpAOM");
	SetClearACC1RedPumpAOM = GetDigitalOutput("SetClearACC1RedPumpAOM");
	SetTriangleBitRedPumpAOM = GetDigitalOutput("SetTriangleBitRedPumpAOM");
	SetFSKBitRedPumpAOM = GetDigitalOutput("SetFSKBitRedPumpAOM");
	SetIntensityPumpDPAOM = GetAnalogOutput("SetIntensityPumpDPAOM");
	SetStartFrequencyPumpDPAOM = GetAnalogOutput("SetStartFrequencyPumpDPAOM");
	SetStopFrequencyPumpDPAOM = GetAnalogOutput("SetStopFrequencyPumpDPAOM");
	SetModulationFrequencyPumpDPAOM = GetAnalogOutput("SetModulationFrequencyPumpDPAOM");
	SetFSKModePumpDPAOM = GetAnalogOutput("SetFSKModePumpDPAOM");
	SetRampRateClockPumpDPAOM = GetAnalogOutput("SetRampRateClockPumpDPAOM");
	SetClearACC1PumpDPAOM = GetDigitalOutput("SetClearACC1PumpDPAOM");
	SetTriangleBitPumpDPAOM = GetDigitalOutput("SetTriangleBitPumpDPAOM");
	SetFSKBitPumpDPAOM = GetDigitalOutput("SetFSKBitPumpDPAOM");
	SetFrequencyBlueMOTDPAOM = GetAnalogOutput("SetFrequencyBlueMOTDPAOM");
	SetIntensityBlueMOTDPAOM = GetAnalogOutput("SetIntensityBlueMOTDPAOM");
	SetFrequencyBlueDetectionDPAOM = GetAnalogOutput("SetFrequencyBlueDetectionDPAOM");
	SetIntensityBlueDetectionDPAOM = GetAnalogOutput("SetIntensityBlueDetectionDPAOM");
	SetFrequencyLatticeAOM = GetAnalogOutput("SetFrequencyLatticeAOM");
	SetIntensityLatticeAOM = GetAnalogOutput("SetIntensityLatticeAOM");
	SetFrequencyLatticeEOM = GetAnalogOutput("SetFrequencyLatticeEOM");
	SetIntensityLatticeEOM = GetAnalogOutput("SetIntensityLatticeEOM");
	SetFrequencyCh0ClockPDHDDS = GetAnalogOutput("SetFrequencyCh0ClockPDHDDS");
	SetIntensityCh0ClockPDHDDS = GetAnalogOutput("SetIntensityCh0ClockPDHDDS");
	SetFrequencyCh1ClockPDHDDS = GetAnalogOutput("SetFrequencyCh1ClockPDHDDS");
	SetIntensityCh1ClockPDHDDS = GetAnalogOutput("SetIntensityCh1ClockPDHDDS");
	SetPhaseCh1ClockPDHDDS = GetAnalogOutput("SetPhaseCh1ClockPDHDDS");
	SetIntensityUserIOTestDDSAD9854_0 = GetAnalogOutput("SetIntensityUserIOTestDDSAD9854_0");
	SetStartFrequencyTuningWordUserIOTestDDSAD9854_0 = GetAnalogOutput("SetStartFrequencyTuningWordUserIOTestDDSAD9854_0");
	SetStopFrequencyTuningWordUserIOTestDDSAD9854_0 = GetAnalogOutput("SetStopFrequencyTuningWordUserIOTestDDSAD9854_0");
	SetModulationFrequencyUserIOTestDDSAD9854_0 = GetAnalogOutput("SetModulationFrequencyUserIOTestDDSAD9854_0");
	SetFSKModeUserIOTestDDSAD9854_0 = GetAnalogOutput("SetFSKModeUserIOTestDDSAD9854_0");
	SetRampRateClockUserIOTestDDSAD9854_0 = GetAnalogOutput("SetRampRateClockUserIOTestDDSAD9854_0");
	SetClearACC1UserIOTestDDSAD9854_0 = GetDigitalOutput("SetClearACC1UserIOTestDDSAD9854_0");
	SetTriangleBitUserIOTestDDSAD9854_0 = GetDigitalOutput("SetTriangleBitUserIOTestDDSAD9854_0");
	SetFSKBitUserIOTestDDSAD9854_0 = GetDigitalOutput("SetFSKBitUserIOTestDDSAD9854_0");
	SetFrequencyUserIOTestDDSAD9858_0 = GetAnalogOutput("SetFrequencyUserIOTestDDSAD9858_0");
	SetAttenuationUserIOTestDDSAD9858_0 = GetAnalogOutput("SetAttenuationUserIOTestDDSAD9858_0");
	SetFrequencyCh0UserIOTestDDSAD9958_0 = GetAnalogOutput("SetFrequencyCh0UserIOTestDDSAD9958_0");
	SetIntensityCh0UserIOTestDDSAD9958_0 = GetAnalogOutput("SetIntensityCh0UserIOTestDDSAD9958_0");
	SetFrequencyCh1UserIOTestDDSAD9958_0 = GetAnalogOutput("SetFrequencyCh1UserIOTestDDSAD9958_0");
	SetIntensityCh1UserIOTestDDSAD9958_0 = GetAnalogOutput("SetIntensityCh1UserIOTestDDSAD9958_0");
	SetPhaseCh1UserIOTestDDSAD9958_0 = GetAnalogOutput("SetPhaseCh1UserIOTestDDSAD9958_0");
	SetSpareAnalogOut0 = GetAnalogOutput("SetSpareAnalogOut0");
	SetSpareAnalogOut1 = GetAnalogOutput("SetSpareAnalogOut1");
	SetSpareAnalogOut2 = GetAnalogOutput("SetSpareAnalogOut2");
	SetSpareAnalogOut3 = GetAnalogOutput("SetSpareAnalogOut3");
	SetSpareAnalogOut4 = GetAnalogOutput("SetSpareAnalogOut4");
	SetSpareAnalogOut5 = GetAnalogOutput("SetSpareAnalogOut5");
	SetSpareAnalogOut6 = GetAnalogOutput("SetSpareAnalogOut6");
	SetSpareAnalogOut7 = GetAnalogOutput("SetSpareAnalogOut7");
	SwitchSpareDigitalOut0 = GetDigitalOutput("SwitchSpareDigitalOut0");
	SwitchSpareDigitalOut1 = GetDigitalOutput("SwitchSpareDigitalOut1");
	SwitchSpareDigitalOut2 = GetDigitalOutput("SwitchSpareDigitalOut2");
	SwitchSpareDigitalOut3 = GetDigitalOutput("SwitchSpareDigitalOut3");
	SwitchSpareDigitalOut4 = GetDigitalOutput("SwitchSpareDigitalOut4");
	SwitchSpareDigitalOut5 = GetDigitalOutput("SwitchSpareDigitalOut5");
	SwitchSpareDigitalOut6 = GetDigitalOutput("SwitchSpareDigitalOut6");
	SwitchSpareDigitalOut7 = GetDigitalOutput("SwitchSpareDigitalOut7");
	SwitchSpareDigitalOut8 = GetDigitalOutput("SwitchSpareDigitalOut8");
	SwitchSpareDigitalOut9 = GetDigitalOutput("SwitchSpareDigitalOut9");
	SwitchSpareDigitalOut10 = GetDigitalOutput("SwitchSpareDigitalOut10");
	SwitchSpareDigitalOut11 = GetDigitalOutput("SwitchSpareDigitalOut11");
	SwitchSpareDigitalOut12 = GetDigitalOutput("SwitchSpareDigitalOut12");
	SwitchSpareDigitalOut13 = GetDigitalOutput("SwitchSpareDigitalOut13");
	SwitchSpareDigitalOut14 = GetDigitalOutput("SwitchSpareDigitalOut14");
	SwitchSpareDigitalOut15 = GetDigitalOutput("SwitchSpareDigitalOut15");
	SwitchExtraClockShutter0 = GetDigitalOutput("SwitchExtraClockShutter0");
	SwitchExtraClockShutter1 = GetDigitalOutput("SwitchExtraClockShutter1");
	SwitchExtraClockShutter2 = GetDigitalOutput("SwitchExtraClockShutter2");
	SwitchExtraClockShutter3 = GetDigitalOutput("SwitchExtraClockShutter3");
	SwitchExtraClockShutter4 = GetDigitalOutput("SwitchExtraClockShutter4");
	SwitchAdditionalShutter0 = GetDigitalOutput("SwitchAdditionalShutter0");
	SwitchAdditionalShutter1 = GetDigitalOutput("SwitchAdditionalShutter1");
	SwitchAdditionalShutter2 = GetDigitalOutput("SwitchAdditionalShutter2");
	SwitchAdditionalShutter3 = GetDigitalOutput("SwitchAdditionalShutter3");
	SwitchAdditionalShutter4 = GetDigitalOutput("SwitchAdditionalShutter4");
	SwitchAdditionalShutter5 = GetDigitalOutput("SwitchAdditionalShutter5");
	SwitchAdditionalShutter6 = GetDigitalOutput("SwitchAdditionalShutter6");
	SwitchAdditionalShutter7 = GetDigitalOutput("SwitchAdditionalShutter7");
}
